app:
  web-client:
    fileService: {
      protocol: ${APP_FILE_SERVICE_HTTP_PROTOCOL},
      host: ${APP_FILE_SERVICE_HOST},
      port: ${APP_FILE_SERVICE_PORT}
    }
    unoconv: {
      protocol: ${APP_UNOCONV_HTTP_PROTOCOL},
      host: ${APP_UNOCONV_HOST},
      port: ${APP_UNOCONV_PORT}
    }
  cdc:
    publication-name: "transactional_outbox_pub"
    slot-name: "debezium_doc_generator_service_slot"
    name: "postgres-transactional-outbox-connector"
    plugin-name: "pgoutput"
    offset-storage-class: "org.apache.kafka.connect.storage.FileOffsetBackingStore"
    offset-storage-file-name: ${APP_CDC_OFFSET_STORAGE_FILE_FILENAME}
    offset-storage-file-folder-path: ${APP_CDC_OFFSET_STORAGE_FILE_FOLDER_PATH}
    offset-flush-interval-millis: 60000
    topic-prefix: ${APP_CDC_TOPIC_PREFIX}
    db-host: ${APP_POSTGRES_HOSTNAME}
    db-port: ${APP_POSTGRES_PORT}
    db-user: ${APP_POSTGRES_USER}
    db-password: ${APP_POSTGRES_PASSWORD}
    db-name: ${APP_POSTGRES_DB}
    schema-include-list: "public"
    table-include-list: "public.transactional_outbox"
    column-include-list: "public.transactional_outbox.id,public.transactional_outbox.name,public.transactional_outbox.topic,public.transactional_outbox.json,public.transactional_outbox.status,public.transactional_outbox.created_at"

spring:
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      jdbc-url: $POSTGRES_JDBC_URL
      password: POSTGRES_PASSWORD
      username: POSTGRES_USERNAME
      driver-class-name: org.postgresql.Driver
    url: $POSTGRES_JDBC_URL
  data:
    r2dbc:
      repositories:
        enabled: true
